default:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:

    ### Local Target - dev
    # Target that combines models under schemas prefixed with DEV_<USERNAME>
    # For use with user account locally during development
    # This target uses your dev workspace environment.
    # This target uses your user account and password, which you can set in the 
    # environment variable: SNOWFLAKE_PASSWORD
    dev:
      type: snowflake
      account: "something.com"

      # browser-based SSO
      user: "{{ cookiecutter.USERNAME }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      role: "TESTDBTPROJECT_DEV_ADMIN"
      database: "TESTDBTPROJECT_DEV"
      warehouse: "TESTDBTPROJECT_DEV_WH"
      schema: "DEV_{{ cookiecutter.USERNAME }}"
      threads: 4
      query_tag: dbt-dev

    # CICD Target - this is for CI testing in the DEV environment
    # Models will be created inside schemas that are named based
    # on the github feature branch (requires branch name to be stored 
    # in BUILD_BRANCH environment variable). 
    # This target relies on the use of a service account user and private key auth
    dev_ci:
      type: snowflake
      account: "something.com"

      user: "TESTDBTPROJECT_DEV_SA"
      private_key_path: "private.key"

      role: "TESTDBTPROJECT_DEV_ADMIN"
      database: "TESTDBTPROJECT_DEV"
      warehouse: "TESTDBTPROJECT_DEV_CI_WH"

      schema: "CI_{{ env_var('BUILD_BRANCH') | upper }}"
      threads: 4
      query_tag: dbt-ci

    # CICD Target - This is for deployment into the UAT environment
    # Models will be created inside schemas named based on the custom schemas
    # Project level schema settings in profiles.yml will be ignored (i.e. no contatenation)
    # This target relies on the use of a service account user and private key auth
    uat:
      type: snowflake
      account: "something.com"

      user: "TESTDBTPROJECT_UAT_SA"
      private_key_path: "private.key"

      role: "TESTDBTPROJECT_UAT_ADMIN"
      database: "TESTDBTPROJECT_UAT"
      warehouse: "TESTDBTPROJECT_UAT_WH"

      schema: "testdbtproject"
      threads: 4
      query_tag: dbt-uat

    # CICD Target - This is for deployment into the PROD environment
    # Models will be created inside schemas specified in the model configs
    # Project level schema settings in profiles.yml will be ignored (i.e. no contatenation)
    # This target relies on the use of a service account user and private key auth
    prod:
      type: snowflake
      account: "something.com"

      user: "TESTDBTPROJECT_PROD_SA"
      private_key_path: "private.key"

      role: "TESTDBTPROJECT_PROD_ADMIN"
      database: "TESTDBTPROJECT_PROD"
      warehouse: "TESTDBTPROJECT_PROD_WH"

      schema: "testdbtproject"
      threads: 4
      query_tag: dbt-prod
